-- V1: accounts. Identity tables follow ASP.NET Core Identity schema version 2
-- (no passkeys), with snake_case names mapped in AppDbContext.

CREATE TABLE roles (
    id                 uuid PRIMARY KEY,
    name               varchar(256),
    normalized_name    varchar(256),
    concurrency_stamp  text
);
CREATE UNIQUE INDEX ux_roles_normalized_name ON roles (normalized_name);

CREATE TABLE users (
    id                       uuid PRIMARY KEY,
    user_name                varchar(256),
    normalized_user_name     varchar(256),
    email                    varchar(256),
    normalized_email         varchar(256),
    email_confirmed          boolean NOT NULL DEFAULT false,
    password_hash            text,
    security_stamp           text,
    concurrency_stamp        text,
    phone_number             text,
    phone_number_confirmed   boolean NOT NULL DEFAULT false,
    two_factor_enabled       boolean NOT NULL DEFAULT false,
    lockout_end              timestamptz,
    lockout_enabled          boolean NOT NULL DEFAULT true,
    access_failed_count      integer NOT NULL DEFAULT 0,
    -- app columns
    is_guest                 boolean NOT NULL DEFAULT false,
    created_at               timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_users_normalized_user_name ON users (normalized_user_name);
CREATE INDEX ix_users_normalized_email ON users (normalized_email);

CREATE TABLE role_claims (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     uuid NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    claim_type  text,
    claim_value text
);
CREATE INDEX ix_role_claims_role_id ON role_claims (role_id);

CREATE TABLE user_claims (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    claim_type  text,
    claim_value text
);
CREATE INDEX ix_user_claims_user_id ON user_claims (user_id);

CREATE TABLE user_logins (
    login_provider        varchar(128) NOT NULL,
    provider_key          varchar(128) NOT NULL,
    provider_display_name text,
    user_id               uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);
CREATE INDEX ix_user_logins_user_id ON user_logins (user_id);

CREATE TABLE user_roles (
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);

CREATE TABLE user_tokens (
    user_id        uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    login_provider varchar(128) NOT NULL,
    name           varchar(128) NOT NULL,
    value          text,
    PRIMARY KEY (user_id, login_provider, name)
);

-- Profile collected at registration; powers filtered stats and leaderboards later.
CREATE TABLE user_profiles (
    user_id          uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    display_name     varchar(40) NOT NULL,
    country_code     char(2),
    birth_year       smallint CHECK (birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100),
    learner_profile  varchar(40),
    time_zone        varchar(64),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Opaque refresh tokens; only a SHA-256 hash is stored.
CREATE TABLE refresh_tokens (
    id           uuid PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   varchar(64) NOT NULL UNIQUE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    revoked_at   timestamptz,
    replaced_by  uuid
);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);

-- Reviewer and admin accounts exist only through invitations.
CREATE TABLE invites (
    id           uuid PRIMARY KEY,
    email        varchar(256) NOT NULL,
    role_name    varchar(32) NOT NULL CHECK (role_name IN ('Reviewer', 'Admin')),
    token_hash   varchar(64) NOT NULL UNIQUE,
    created_by   uuid REFERENCES users (id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    accepted_at  timestamptz
);
CREATE INDEX ix_invites_email ON invites (email);

INSERT INTO roles (id, name, normalized_name, concurrency_stamp) VALUES
    ('7b1d2a10-0000-4000-8000-000000000001', 'Learner',  'LEARNER',  'seed-learner'),
    ('7b1d2a10-0000-4000-8000-000000000002', 'Reviewer', 'REVIEWER', 'seed-reviewer'),
    ('7b1d2a10-0000-4000-8000-000000000003', 'Admin',    'ADMIN',    'seed-admin');
