-- V3: ASP.NET Core Data Protection keys. Stored in the database so password-reset
-- tokens and sign-in cookies survive restarts and redeploys on hosts with an ephemeral disk.

CREATE TABLE data_protection_keys (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendly_name varchar(512),
    xml           text
);
